### PR TITLE
Status Change

### PR DESCRIPTION
**Pull request by matheushf**
Status change when clicking on the `<li>`
Added color and Delete option

#1

### CODE REVIEW

**Comment by karate** [comment]
Thank you for your time @matheushf, but I don't think that works. The jinja tags inside `index.html` are not used. The initial tasks are rendered on page load by `get_tasks()` in `script.js` so you have to edit the ajax calls there in order to edit the `li` markup and add the `span.delete`.

Also, even after doing this, I still didn't managed to get you commit to work.

**Comment by matheushf** [comment]
I saw that it wasn't showing up to the `li` and was going to fix it later, but I had to sleep. Actually I spent some time at and the rest of the code isn't wrong at all, you should just have told me that it didn't work and I would fix it instead of making me spend time for nothing.

**Comment by karate** [comment]
I'm really sorry @matheushf. We have different timezones. After I created the Issue, I wrote about 90% of the code myself, and then went to bed without commiting anything. When I woke up I saw both your comment and your PR. I tried it and I saw it didn't wok. I tried to make it work but I didn't succeed, so I finished my code and commited.

I'm sorry again if I was too hasty. I'll create some more `hacktoberfest` issues soon.

**Comment by matheushf** [comment]
Oh no dude sorry for that, it's ok :)

**Pull request closed without merging**
